# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Render an interactive ranked-bar chart of a screen's matched symbols (HTML).

OPTIONAL visualization step -- run it only when a chart helps the answer or the
user asks to see/visualize the screen. The ranked text table (scripts/screen.py)
is the primary output and never depends on this file.

Pipeline: provider.run_screen (robust batch fetch) -> provider.apply_filter
(filter + rank) -> viz.render_screen_chart (self-contained interactive HTML).

Usage:
    python scripts/chart.py --index sp500 --filter "rsi<30" --out sp500-oversold.html
    python scripts/chart.py --index nasdaq100 --filter "price>ema200" --top 15
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import provider
import viz


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Ranked horizontal-bar screen chart (HTML)."
    )
    ap.add_argument("--index", choices=["sp500", "nasdaq100"], required=True)
    ap.add_argument("--filter", required=True, help="e.g. 'rsi<30' or 'price>ema200'")
    ap.add_argument(
        "--period", default="1y", help="1y+ so EMA200 has enough history to compute"
    )
    ap.add_argument("--top", type=int, default=25, help="max bars to render")
    ap.add_argument("--out", default="")
    a = ap.parse_args()

    screen = provider.run_screen(a.index, a.period)
    matched, meta = provider.apply_filter(screen["rows"], a.filter)
    top = matched[: a.top]
    bars = [
        {
            "symbol": r["symbol"],
            "name": r["name"],
            "sector": r["sector"],
            "rank_value": r["rank_value"],
            "rank_display": r["rank_display"],
        }
        for r in top
    ]

    doc = viz.render_screen_chart(
        a.index,
        a.filter,
        str(meta["metric_label"]),
        bars,
        str(screen["as_of"]),
        a.period,
    )
    out = a.out or f"{a.index}-screen.html"
    Path(out).write_text(doc)
    print(
        f"wrote {out} ({len(doc)} bytes, {len(bars)}/{len(matched)} shown, "
        f"{len(screen['skipped'])} skipped, as of {screen['as_of']})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
