# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Pure-Python technical indicators (no third-party dependencies).

Each function takes a list of floats ordered oldest -> newest and returns a list
of the same length, with None during the warm-up period. Shared by the screen
and charting scripts so the math lives in exactly one place.
"""

from __future__ import annotations

Series = list[float]
Line = list[float | None]


def sma(values: Series, period: int) -> Line:
    out: Line = [None] * len(values)
    if period <= 0:
        return out
    run = 0.0
    for i, v in enumerate(values):
        run += v
        if i >= period:
            run -= values[i - period]
        if i >= period - 1:
            out[i] = run / period
    return out


def ema(values: Series, period: int) -> Line:
    out: Line = [None] * len(values)
    if len(values) < period or period <= 0:
        return out
    k = 2 / (period + 1)
    prev = sum(values[:period]) / period  # seed with SMA
    out[period - 1] = prev
    for i in range(period, len(values)):
        prev = values[i] * k + prev * (1 - k)
        out[i] = prev
    return out


def rsi(values: Series, period: int = 14) -> Line:
    out: Line = [None] * len(values)
    if len(values) <= period:
        return out

    def rsi_val(ag: float, al: float) -> float:
        if al == 0:
            return 100.0
        return 100 - 100 / (1 + ag / al)

    gains = losses = 0.0
    for i in range(1, period + 1):
        ch = values[i] - values[i - 1]
        gains += max(ch, 0.0)
        losses += max(-ch, 0.0)
    avg_gain, avg_loss = gains / period, losses / period
    out[period] = rsi_val(avg_gain, avg_loss)
    for i in range(period + 1, len(values)):
        ch = values[i] - values[i - 1]
        avg_gain = (avg_gain * (period - 1) + max(ch, 0.0)) / period
        avg_loss = (avg_loss * (period - 1) + max(-ch, 0.0)) / period
        out[i] = rsi_val(avg_gain, avg_loss)
    return out


def macd(
    values: Series, fast: int = 12, slow: int = 26, signal: int = 9
) -> dict[str, Line]:
    ef, es = ema(values, fast), ema(values, slow)
    line: Line = [
        (a - b) if (a is not None and b is not None) else None for a, b in zip(ef, es)
    ]
    defined = [x for x in line if x is not None]
    sig_defined = ema(defined, signal)
    sig: Line = [None] * len(line)
    j = 0
    for i, x in enumerate(line):
        if x is not None:
            sig[i] = sig_defined[j]
            j += 1
    hist: Line = [
        (m - s) if (m is not None and s is not None) else None
        for m, s in zip(line, sig)
    ]
    return {"macd": line, "signal": sig, "hist": hist}


def bollinger(values: Series, period: int = 20, mult: float = 2.0) -> dict[str, Line]:
    mid = sma(values, period)
    upper: Line = [None] * len(values)
    lower: Line = [None] * len(values)
    for i in range(len(values)):
        m = mid[i]
        if i >= period - 1 and m is not None:
            window = values[i - period + 1 : i + 1]
            sd = (sum((x - m) ** 2 for x in window) / period) ** 0.5
            upper[i] = m + mult * sd
            lower[i] = m - mult * sd
    return {"mid": mid, "upper": upper, "lower": lower}


def cci(highs: Series, lows: Series, closes: Series, period: int = 20) -> Line:
    tp = [(h + l + c) / 3 for h, l, c in zip(highs, lows, closes)]
    out: Line = [None] * len(tp)
    for i in range(len(tp)):
        if i >= period - 1:
            window = tp[i - period + 1 : i + 1]
            m = sum(window) / period
            md = sum(abs(x - m) for x in window) / period
            out[i] = (tp[i] - m) / (0.015 * md) if md else 0.0
    return out


if __name__ == "__main__":  # tiny self-test against a known strictly-rising ramp
    import json

    def r(x: float | None) -> float | None:
        return round(x, 3) if x is not None else None

    ramp = [float(x) for x in range(1, 40)]
    print(
        json.dumps(
            {
                "ema10_last": r(ema(ramp, 10)[-1]),
                "rsi14_last": r(rsi(ramp, 14)[-1]),  # strictly rising -> 100
                "sma5_last": r(sma(ramp, 5)[-1]),
            },
            indent=2,
        )
    )
