# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Robust universe provider for the S&P 500 / NASDAQ-100 screener.

Why this module exists (mirrors the global-stock-analysis provider pattern):
  - Transient fetch failures (HTTP 429, flaky network) are retried with
    exponential backoff and then RE-RAISED -- never swallowed into a silent
    None that would fabricate a passing (or failing) screen result.
  - resolve() reads a value across several candidate keys because the upstream
    feed is inconsistent about field naming; a synonym should not read as null.
  - This is the ONLY module that imports yfinance, so a paid feed (polygon,
    finnhub) can replace it without touching indicators, the screener, or viz.
  - Per-symbol data gaps are handled honestly: a symbol with no EOD data is
    SKIPPED and reported under `skipped`, never assigned a fabricated metric.
"""

from __future__ import annotations

import re
import math
import time
from pathlib import Path
from typing import Any, Callable, Optional, TypeVar

import indicators

T = TypeVar("T")

Constituent = tuple[str, str, str]  # (symbol, name, sector)
Row = dict[str, Any]

_ROOT = Path(__file__).resolve().parent.parent
_TICKER_RE = re.compile(r"[A-Z][A-Z.]{0,5}")
_FILTER_RE = re.compile(r"^\s*([a-z_0-9]+)\s*(<=|>=|<|>)\s*([a-z_0-9.]+)\s*$", re.I)
_METRICS = {"rsi", "close", "price", "ema20", "ema50", "ema200"}


def _retry(fn: Callable[[], T], tries: int = 3, base: float = 0.6) -> T:
    last: Optional[Exception] = None
    for attempt in range(tries):
        try:
            return fn()
        except Exception as exc:  # transient provider error; re-raised if persistent
            last = exc
            time.sleep(base * (2**attempt))
    raise RuntimeError(f"market-data provider failed after {tries} tries: {last}")


def resolve(
    info: dict[str, Any], keys: list[str]
) -> tuple[Optional[Any], Optional[str]]:
    """First populated value across candidate keys -> (value, key_used).

    Returns (None, None) only when EVERY candidate is genuinely absent -- which
    the caller should surface as 'unavailable from source', not as a zero.
    """
    for k in keys:
        v = info.get(k)
        if v is not None and v != "":
            return v, k
    return None, None


def get_info(ticker: str) -> dict[str, Any]:
    import yfinance as yf

    return _retry(lambda: dict(yf.Ticker(ticker).info or {}))


def load_universe(index: str) -> list[Constituent]:
    """Parse references/<index>-constituents.md snapshot -> constituents.

    The snapshot is a DATED, fixed-width table; membership drifts on rebalance,
    so callers must surface the snapshot date. Raises when the file is absent --
    a missing universe is a real error, not an empty screen.
    """
    path = _ROOT / "references" / f"{index}-constituents.md"
    if not path.exists():
        raise FileNotFoundError(
            f"no constituent snapshot for index {index!r} at references/{path.name}"
        )
    out: list[Constituent] = []
    for raw in path.read_text().splitlines():
        if not raw.startswith("    "):  # snapshot rows are indented (code block)
            continue
        parts = re.split(r"\s{2,}", raw.strip())
        if len(parts) >= 3 and _TICKER_RE.fullmatch(parts[0]):
            out.append((parts[0], parts[1], parts[2]))
    return out


def get_close_series(ticker: str, period: str = "1y") -> tuple[list[str], list[float]]:
    """(dates, closes) oldest -> newest. Raises if the symbol has no data."""
    import yfinance as yf

    def _pull() -> Any:
        h = yf.Ticker(ticker).history(period=period, interval="1d")
        if h.empty:
            raise ValueError(f"no market data for {ticker!r} (check symbol/exchange)")
        return h

    hist = _retry(_pull)
    dates: list[str] = []
    closes: list[float] = []
    for idx, row in hist.iterrows():
        px = float(row["Close"])
        if not math.isfinite(px):
            # Yahoo emits NaN placeholder rows (e.g. pre-open); a NaN close would
            # poison every EMA/RSI downstream, so drop the row at the boundary.
            continue
        dates.append(idx.strftime("%Y-%m-%d"))
        closes.append(round(px, 4))
    if not closes:
        raise ValueError(f"only NaN closes for {ticker!r} in the returned window")
    return dates, closes


def metrics_for(ticker: str, period: str = "1y") -> Row:
    """EOD close + latest RSI(14) and EMA 20/50/200 for one symbol.

    Values are the last defined point of each series (None while the indicator
    is still in its warm-up window -- not a fabricated zero).
    """
    dates, closes = get_close_series(ticker, period)
    if not closes:
        raise ValueError(f"empty close series for {ticker!r}")
    return {
        "symbol": ticker,
        "as_of": dates[-1],
        "close": closes[-1],
        "rsi": indicators.rsi(closes, 14)[-1],
        "ema20": indicators.ema(closes, 20)[-1],
        "ema50": indicators.ema(closes, 50)[-1],
        "ema200": indicators.ema(closes, 200)[-1],
    }


def run_screen(index: str, period: str = "1y") -> dict[str, Any]:
    """Batch-fetch the universe and compute per-symbol metrics.

    Symbols whose data cannot be retrieved (persistent 429, delisted, no bars)
    are recorded in `skipped` with the reason and left OUT of `rows` -- the
    screen never invents a value to keep a symbol in the table.
    """
    universe = load_universe(index)
    rows: list[Row] = []
    skipped: list[dict[str, str]] = []
    as_of = ""
    for symbol, name, sector in universe:
        try:
            m = metrics_for(symbol, period)
        except (ValueError, RuntimeError) as exc:
            # intentional best-effort: no EOD data from source -> skip honestly.
            skipped.append({"symbol": symbol, "reason": str(exc)})
            continue
        as_of = str(m["as_of"]) or as_of
        rows.append({"name": name, "sector": sector, **m})
    return {
        "index": index,
        "period": period,
        "as_of": as_of,
        "rows": rows,
        "skipped": skipped,
    }


def _metric(row: Row, name: str) -> Optional[float]:
    key = "close" if name in ("price", "close") else name
    v = row.get(key)
    return float(v) if isinstance(v, (int, float)) else None


def _cmp(a: float, op: str, b: float) -> bool:
    return {"<": a < b, ">": a > b, "<=": a <= b, ">=": a >= b}[op]


def parse_filter(expr: str) -> tuple[str, str, str, bool]:
    """'rsi<30' -> (left, op, right, right_is_metric). Raises on bad syntax."""
    m = _FILTER_RE.match(expr)
    if not m:
        raise ValueError(
            f"cannot parse filter {expr!r} (try 'rsi<30' or 'price>ema200')"
        )
    left, op, right = m.group(1).lower(), m.group(2), m.group(3).lower()
    if left not in _METRICS:
        raise ValueError(f"unknown metric {left!r} in filter (supported: {_METRICS})")
    right_is_metric = right in _METRICS
    if not right_is_metric:
        try:
            float(right)
        except ValueError:
            raise ValueError(
                f"right side {right!r} is neither a number nor a known metric"
            ) from None
    return left, op, right, right_is_metric


def apply_filter(rows: list[Row], expr: str) -> tuple[list[Row], dict[str, Any]]:
    """Keep rows matching `expr`, annotate a ranking value, and sort by it.

    Rows whose needed metric is None (warm-up / no data) are skipped honestly,
    not counted as a match. For a metric-vs-metric filter (e.g. price>ema200)
    the ranking value is the percentage gap; for a threshold it is the metric.
    """
    left, op, right, right_is_metric = parse_filter(expr)
    matched: list[Row] = []
    for row in rows:
        lv = _metric(row, left)
        if lv is None:
            continue
        if right_is_metric:
            rv = _metric(row, right)
            if rv is None or rv == 0:
                continue
            passed = _cmp(lv, op, rv)
            rank_value = (lv - rv) / rv * 100.0
            display = f"{rank_value:+.2f}%"
        else:
            passed = _cmp(lv, op, float(right))
            rank_value = lv
            display = f"{lv:.1f}" if left == "rsi" else f"{lv:,.2f}"
        if passed:
            out_row = dict(row)
            out_row["rank_value"] = rank_value
            out_row["rank_display"] = display
            matched.append(out_row)
    descending = op in (">", ">=")
    matched.sort(key=lambda r: float(r["rank_value"]), reverse=descending)
    if right_is_metric:
        label = f"{left.upper()} vs {right.upper()} (% gap)"
    else:
        label = "RSI(14)" if left == "rsi" else left.upper()
    meta = {"metric_label": label, "filter": expr, "count": len(matched)}
    return matched, meta


if __name__ == "__main__":  # offline self-test (no network): universe + filter math
    import json

    demo: list[Row] = [
        {
            "symbol": "AAA",
            "name": "Alpha",
            "sector": "Tech",
            "close": 100.0,
            "rsi": 22.0,
            "ema20": 96.0,
            "ema50": 92.0,
            "ema200": 88.0,
        },
        {
            "symbol": "BBB",
            "name": "Beta",
            "sector": "Energy",
            "close": 40.0,
            "rsi": 55.0,
            "ema20": 41.0,
            "ema50": 42.0,
            "ema200": 45.0,
        },
        {
            "symbol": "CCC",
            "name": "Gamma",
            "sector": "Health",
            "close": 12.0,
            "rsi": 28.0,
            "ema20": 12.5,
            "ema50": 13.0,
            "ema200": 14.0,
        },
    ]
    oversold, m1 = apply_filter(demo, "rsi<30")
    above, m2 = apply_filter(demo, "price>ema200")
    print(
        json.dumps(
            {
                "sp500_universe": len(load_universe("sp500")),
                "nasdaq100_universe": len(load_universe("nasdaq100")),
                "rsi<30": [r["symbol"] for r in oversold],
                "rsi<30_meta": m1,
                "price>ema200": [(r["symbol"], r["rank_display"]) for r in above],
            },
            indent=2,
        )
    )
