# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Self-contained interactive HTML/SVG chart generator (no third-party deps).

Renders a ranked HORIZONTAL BAR chart of a screen's matched symbols by the
ranking metric into a single HTML file: inline SVG, per-bar hover highlight +
tooltip, a table view, and a light/dark toggle. One sequential accent hue
(--s1) carries all bars (single series -> direct labels, no legend); the axis
and grid stay recessive. Colours come from the data-viz reference palette,
which is already colour-blind validated.

This is the OPTIONAL visualization layer -- the skill renders it only when a
chart helps or the user asks; the ranked text table never depends on it.
"""

from __future__ import annotations

import html
import json
from typing import Any, Optional

# Data-viz reference palette (roles only; light + dark are both selected sets).
PAL = {
    "light": {
        "surface": "#fcfcfb",
        "page": "#f9f9f7",
        "primary": "#0b0b0b",
        "secondary": "#52514e",
        "muted": "#898781",
        "grid": "#e1e0d9",
        "axis": "#c3c2b7",
        "s1": "#2a78d6",
        "s2": "#1baf7a",
        "s3": "#eda100",
        "s4": "#4a3aa7",
        "good": "#006300",
        "bad": "#d03b3b",
        "bandfill": "#e1e0d9",
    },
    "dark": {
        "surface": "#1a1a19",
        "page": "#0d0d0d",
        "primary": "#ffffff",
        "secondary": "#c3c2b7",
        "muted": "#898781",
        "grid": "#2c2c2a",
        "axis": "#383835",
        "s1": "#3987e5",
        "s2": "#199e70",
        "s3": "#c98500",
        "s4": "#9085e9",
        "good": "#0ca30c",
        "bad": "#d03b3b",
        "bandfill": "#2c2c2a",
    },
}

W = 760
MT, MB, ML, MR = 16, 34, 96, 92  # top, bottom, left gutter (symbols), right (values)
RH = 30  # per-bar row height
BARH = 18  # drawn bar thickness
PX0, PX1 = ML, W - MR  # plot x span


def _fmt(v: Optional[float], nd: int = 2) -> str:
    return "-" if v is None else f"{v:,.{nd}f}"


def _nice_ticks(d0: float, d1: float, n: int = 4) -> list[float]:
    if d1 <= d0:
        return [d0]
    return [d0 + (d1 - d0) * t / n for t in range(n + 1)]


def render_screen_chart(
    index: str,
    filter_expr: str,
    metric_label: str,
    bars: list[dict[str, Any]],
    as_of: str,
    period: str,
) -> str:
    """Render the ranked horizontal-bar screen chart as a standalone HTML doc.

    `bars` is already in rank order (best match first); each item carries
    symbol, name, sector, rank_value (float) and rank_display (str).
    """
    n = len(bars)
    values = [float(b["rank_value"]) for b in bars]
    vmin = min(values) if values else 0.0
    vmax = max(values) if values else 1.0
    d0 = min(0.0, vmin)
    d1 = max(0.0, vmax)
    if d1 == d0:
        d1 = d0 + 1.0

    plot_h = max(RH, n * RH)
    H = MT + plot_h + MB

    def xscale(v: float) -> float:
        return PX0 + (v - d0) / (d1 - d0) * (PX1 - PX0)

    zero_x = xscale(0.0)

    # recessive vertical gridlines + value axis labels
    grid: list[str] = []
    for t in _nice_ticks(d0, d1):
        x = xscale(t)
        grid.append(
            f'<line x1="{x:.1f}" y1="{MT}" x2="{x:.1f}" y2="{MT + plot_h}" class="grid"/>'
        )
        grid.append(
            f'<text x="{x:.1f}" y="{MT + plot_h + 16}" class="xtick">{_fmt(t, 1)}</text>'
        )
    # zero baseline (the axis anchor) drawn a touch stronger than the grid
    axis = (
        f'<line x1="{zero_x:.1f}" y1="{MT}" x2="{zero_x:.1f}" y2="{MT + plot_h}" '
        f'class="axis"/>'
    )

    bar_svg: list[str] = []
    for i, b in enumerate(bars):
        v = float(b["rank_value"])
        y_top = MT + i * RH + (RH - BARH) / 2
        y_mid = MT + i * RH + RH / 2
        x_val = xscale(v)
        x0 = min(zero_x, x_val)
        w = abs(x_val - zero_x)
        sym = html.escape(str(b["symbol"]))
        disp = html.escape(str(b["rank_display"]))
        bar_svg.append(
            f'<rect x="{x0:.1f}" y="{y_top:.1f}" width="{max(w, 1):.1f}" '
            f'height="{BARH}" rx="3" fill="var(--s1)"/>'
        )
        # direct label 1: symbol in the left gutter
        bar_svg.append(
            f'<text x="{ML - 8}" y="{y_mid + 4:.1f}" class="barlab">{sym}</text>'
        )
        # direct label 2: value at the growing end of the bar
        if v >= 0:
            bar_svg.append(
                f'<text x="{x_val + 6:.1f}" y="{y_mid + 4:.1f}" class="vallab" '
                f'style="text-anchor:start">{disp}</text>'
            )
        else:
            bar_svg.append(
                f'<text x="{x_val - 6:.1f}" y="{y_mid + 4:.1f}" class="vallab" '
                f'style="text-anchor:end">{disp}</text>'
            )

    empty = (
        ""
        if bars
        else (
            f'<text x="{W / 2:.0f}" y="{MT + plot_h / 2:.0f}" class="empty">'
            f"No symbols matched this filter</text>"
        )
    )

    # embedded data for the hover layer (rendered client-side via textContent)
    data = {
        "rows": [
            {
                "sym": str(b["symbol"]),
                "name": str(b["name"]),
                "sector": str(b["sector"]),
                "disp": str(b["rank_display"]),
                "y0": round(MT + i * RH, 1),
            }
            for i, b in enumerate(bars)
        ],
        "rh": RH,
        "mt": MT,
        "label": metric_label,
    }

    trows = "".join(
        f"<tr><td>{i + 1}</td><td>{html.escape(str(b['symbol']))}</td>"
        f"<td>{html.escape(str(b['name']))}</td>"
        f"<td>{html.escape(str(b['sector']))}</td>"
        f"<td>{html.escape(str(b['rank_display']))}</td></tr>"
        for i, b in enumerate(bars)
    )

    sub = (
        f"{metric_label} · filter {filter_expr} · {n} matched · "
        f"{period} · as of {as_of}"
    )

    def css_vars(mode: str) -> str:
        return ";".join(f"--{k}:{v}" for k, v in PAL[mode].items())

    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(index.upper())} screen — {html.escape(filter_expr)}</title>
<style>
  :root{{{css_vars("light")};--panel:#fff}}
  html[data-theme="dark"]{{{css_vars("dark")};--panel:#111}}
  @media (prefers-color-scheme:dark){{html:not([data-theme="light"]){{{css_vars("dark")};--panel:#111}}}}
  *{{box-sizing:border-box}} body{{margin:0;background:var(--page);color:var(--primary);
    font-family:system-ui,-apple-system,"Segoe UI",sans-serif}}
  .wrap{{max-width:820px;margin:0 auto;padding:20px}}
  .head{{display:flex;justify-content:space-between;align-items:flex-end;gap:12px;flex-wrap:wrap}}
  h1{{font-size:20px;margin:0}} .sub{{color:var(--secondary);font-size:13px;margin-top:2px}}
  .hero{{text-align:right}} .hero .ct{{font-size:28px;font-weight:700}}
  .hero .lb{{font-size:13px;color:var(--secondary)}}
  .card{{background:var(--surface);border:1px solid var(--grid);border-radius:12px;padding:10px;position:relative;margin-top:12px}}
  svg{{display:block;width:100%;height:auto;touch-action:none}}
  .grid{{stroke:var(--grid);stroke-width:1}} .axis{{stroke:var(--axis);stroke-width:1.25}}
  .xtick{{fill:var(--muted);font-size:10.5px;text-anchor:middle;font-variant-numeric:tabular-nums}}
  .barlab{{fill:var(--secondary);font-size:12px;font-weight:600;text-anchor:end}}
  .vallab{{fill:var(--primary);font-size:11.5px;font-variant-numeric:tabular-nums}}
  .empty{{fill:var(--muted);font-size:13px;text-anchor:middle}}
  #hi{{fill:var(--s1);opacity:0}}
  .tip{{position:absolute;pointer-events:none;background:var(--panel);border:1px solid var(--grid);
    border-radius:8px;padding:8px 10px;font-size:12px;opacity:0;transform:translate(-50%,-115%);
    white-space:nowrap;box-shadow:0 4px 14px rgba(0,0,0,.18);font-variant-numeric:tabular-nums}}
  .tip b{{display:block;margin-bottom:3px;font-size:12px}} .tip span{{color:var(--secondary)}}
  .bar{{display:flex;gap:8px;margin:14px 0 4px}}
  button{{background:var(--surface);color:var(--primary);border:1px solid var(--grid);border-radius:8px;
    padding:6px 12px;font-size:12.5px;cursor:pointer}} button:hover{{border-color:var(--s1)}}
  table{{border-collapse:collapse;width:100%;font-size:12px;font-variant-numeric:tabular-nums;margin-top:8px}}
  th,td{{text-align:left;padding:4px 8px;border-bottom:1px solid var(--grid)}} th{{color:var(--secondary)}}
  td:last-child,th:last-child{{text-align:right}} #tableview{{display:none}}
</style></head>
<body><div class="wrap">
  <div class="head">
    <div><h1>{html.escape(index.upper())} screen</h1>
      <div class="sub">{html.escape(sub)}</div></div>
    <div class="hero"><div class="ct">{n}</div>
      <div class="lb">matched</div></div>
  </div>
  <div class="card" id="card">
    <svg id="svg" viewBox="0 0 {W} {H}" preserveAspectRatio="xMidYMid meet"
         role="img" aria-label="Ranked screen results for {html.escape(index.upper())}">
      <rect id="hi" x="{PX0}" y="0" width="{PX1 - PX0}" height="{RH}"/>
      {"".join(grid)}{axis}
      {"".join(bar_svg)}{empty}
    </svg>
    <div class="tip" id="tip"></div>
  </div>
  <div class="bar">
    <button id="tbtn">Table view</button>
    <button id="thm">Toggle light/dark</button>
  </div>
  <div id="tableview"><table><thead><tr><th>#</th><th>Symbol</th><th>Name</th>
    <th>Sector</th><th>{html.escape(metric_label)}</th></tr></thead>
    <tbody>{trows}</tbody></table></div>
</div>
<script>
const D={json.dumps(data)};
const svg=document.getElementById('svg'),card=document.getElementById('card'),
  tip=document.getElementById('tip'),hi=document.getElementById('hi');
const VBH={H};
function move(ev){{
  const r=svg.getBoundingClientRect();
  if(!D.rows.length){{return}}
  const sy=(ev.clientY-r.top)/r.height*VBH;
  let i=Math.floor((sy-D.mt)/D.rh);
  if(i<0||i>=D.rows.length){{tip.style.opacity=0;hi.style.opacity=0;return}}
  const row=D.rows[i];
  hi.setAttribute('y',row.y0);hi.style.opacity=.12;
  tip.textContent='';
  const b=document.createElement('b');b.textContent=row.sym;tip.appendChild(b);
  const meta=document.createElement('span');
  meta.textContent=row.name+' · '+row.sector;tip.appendChild(meta);
  tip.appendChild(document.createElement('br'));
  tip.appendChild(document.createTextNode(D.label+': '+row.disp));
  tip.style.opacity=1;
  const cardR=card.getBoundingClientRect();
  tip.style.left=(ev.clientX-cardR.left)+'px';
  tip.style.top=(ev.clientY-r.top)+'px';
}}
svg.addEventListener('pointermove',move);
svg.addEventListener('pointerleave',()=>{{tip.style.opacity=0;hi.style.opacity=0}});
document.getElementById('tbtn').onclick=()=>{{const t=document.getElementById('tableview');
  t.style.display=t.style.display==='block'?'none':'block'}};
document.getElementById('thm').onclick=()=>{{const h=document.documentElement;
  const cur=h.getAttribute('data-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');
  h.setAttribute('data-theme',cur==='dark'?'light':'dark')}};
</script></body></html>"""
