# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Render an interactive HTML ETF holdings / overlap chart.

OPTIONAL visualization step -- run it only when a chart helps the answer or the
user asks to see/visualize. The text analysis never depends on it.

Pipeline: provider.get_etf_profile (robust fetch) -> viz.render_* (self-contained
interactive HTML: holdings composition, or a two-ETF overlap when --compare).

Usage:
    python scripts/chart.py --ticker QQQ --out QQQ.html
    python scripts/chart.py --ticker VTI --compare VOO --out vti-voo.html
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

import provider
import viz


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Interactive ETF holdings/overlap chart (HTML)."
    )
    ap.add_argument("--ticker", required=True)
    ap.add_argument("--compare", default="", help="second ETF ticker -> overlap chart")
    ap.add_argument("--top", type=int, default=15, help="how many holdings to plot")
    ap.add_argument("--out", default="")
    a = ap.parse_args()

    as_of = datetime.date.today().isoformat()
    profile = provider.get_etf_profile(a.ticker)

    if a.compare:
        other = provider.get_etf_profile(a.compare)
        overlap = provider.holdings_overlap(profile["holdings"], other["holdings"])
        doc = viz.render_overlap_chart(profile, other, overlap, as_of, a.top)
        default = f"{a.ticker.upper()}-{a.compare.upper()}-overlap.html"
    else:
        doc = viz.render_holdings_chart(profile, as_of, a.top)
        default = f"{a.ticker.upper()}.html"

    out = a.out or default
    Path(out).write_text(doc)
    print(f"wrote {out} ({len(doc)} bytes, as of {as_of})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
