# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Shared HTML shell for the ETF charts: palette, CSS, JS, and page assembler.

Split out of viz.py so each module stays small; viz.py builds the SVG marks and
imports document() + the formatters from here. The generated page is fully
self-contained (inline CSS/JS, no external assets).

XSS-safe by construction: dynamic tooltip nodes are built with DOM textContent
(never innerHTML), and the embedded JSON escapes < > & (plus JS line separators)
so a free-text holding name containing </script> cannot break out of the inline
<script> block while staying valid JSON.
"""

from __future__ import annotations

import html
import json
import math
from typing import Any, Optional

# Data-viz reference palette (roles only; light + dark are both CVD-validated sets).
PAL = {
    "light": {
        "surface": "#fcfcfb",
        "page": "#f9f9f7",
        "primary": "#0b0b0b",
        "secondary": "#52514e",
        "muted": "#898781",
        "grid": "#e1e0d9",
        "axis": "#c3c2b7",
        "s1": "#2a78d6",
        "s2": "#1baf7a",
        "s3": "#eda100",
        "s4": "#4a3aa7",
        "good": "#006300",
        "bad": "#d03b3b",
        "bandfill": "#e1e0d9",
    },
    "dark": {
        "surface": "#1a1a19",
        "page": "#0d0d0d",
        "primary": "#ffffff",
        "secondary": "#c3c2b7",
        "muted": "#898781",
        "grid": "#2c2c2a",
        "axis": "#383835",
        "s1": "#3987e5",
        "s2": "#199e70",
        "s3": "#c98500",
        "s4": "#9085e9",
        "good": "#0ca30c",
        "bad": "#d03b3b",
        "bandfill": "#2c2c2a",
    },
}

W, ML, MR, MT = 960, 118, 92, 20  # width, left labels, right values, top pad


def esc(s: object) -> str:
    return html.escape(str(s))


def pct(v: Optional[float], nd: int = 2) -> str:
    return "n/a" if v is None else f"{v:.{nd}f}%"


def money(v: Optional[float]) -> str:
    if v is None:
        return "n/a"
    v = float(v)
    for unit, div in (("T", 1e12), ("B", 1e9), ("M", 1e6), ("K", 1e3)):
        if abs(v) >= div:
            return f"${v / div:,.2f}{unit}"
    return f"${v:,.0f}"


def nice_max(v: float) -> float:
    """Smallest 'nice' axis ceiling >= v (1/2/2.5/5/10 x power of ten)."""
    if v <= 0:
        return 1.0
    base = 10 ** math.floor(math.log10(v))
    for m in (1.0, 2.0, 2.5, 5.0, 10.0):
        if v <= m * base:
            return m * base
    return 10.0 * base


_STYLE = """
  :root{__L__;--panel:#fff} html[data-theme="dark"]{__D__;--panel:#111}
  @media (prefers-color-scheme:dark){html:not([data-theme="light"]){__D__;--panel:#111}}
  *{box-sizing:border-box} .wrap{max-width:1000px;margin:0 auto;padding:20px}
  body{margin:0;background:var(--page);color:var(--primary);font-family:system-ui,-apple-system,"Segoe UI",sans-serif}
  .head{display:flex;justify-content:space-between;align-items:flex-end;gap:12px;flex-wrap:wrap}
  h1{font-size:20px;margin:0} .sub{color:var(--secondary);font-size:13px;margin-top:2px}
  .hero{display:flex;gap:18px;text-align:right} .metric{display:flex;flex-direction:column}
  .ml{font-size:11px;color:var(--secondary)} .mv{font-size:22px;font-weight:700;font-variant-numeric:tabular-nums}
  .mv.up{color:var(--good)} .mv.down{color:var(--bad)} .mv.muted{color:var(--muted);font-size:15px;font-weight:600}
  .legend{display:flex;gap:14px;flex-wrap:wrap;margin:12px 0 4px;font-size:12px;color:var(--secondary)}
  .lg i{display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:5px;vertical-align:middle}
  .card{background:var(--surface);border:1px solid var(--grid);border-radius:12px;padding:10px;position:relative}
  .overflow{overflow-x:auto} svg{display:block;width:100%;height:auto;touch-action:none}
  .grid{stroke:var(--grid);stroke-width:1} .axis{stroke:var(--axis);stroke-width:1}
  .xtick{fill:var(--muted);font-size:10.5px;text-anchor:middle;font-variant-numeric:tabular-nums}
  .rowlab{fill:var(--secondary);font-size:11.5px;text-anchor:end;font-variant-numeric:tabular-nums}
  .barval{fill:var(--secondary);font-size:10.5px;font-variant-numeric:tabular-nums}
  .bar{stroke:var(--surface);stroke-width:.5} .note{fill:var(--muted);font-size:12px}
  #hl{fill:var(--s1);opacity:0} .hit{fill:transparent;cursor:crosshair}
  .tip{position:absolute;pointer-events:none;background:var(--panel);border:1px solid var(--grid);border-radius:8px;
    padding:8px 10px;font-size:12px;opacity:0;transform:translate(-50%,-115%);white-space:nowrap;
    box-shadow:0 4px 14px rgba(0,0,0,.18);font-variant-numeric:tabular-nums}
  .tip b{display:block;margin-bottom:4px;font-size:11px;color:var(--secondary)} .tip div{line-height:1.5}
  .tip s{display:inline-block;width:8px;height:8px;border-radius:2px;margin-right:5px}
  .barctl{display:flex;gap:8px;margin:14px 0 4px}
  button{background:var(--surface);color:var(--primary);border:1px solid var(--grid);border-radius:8px;
    padding:6px 12px;font-size:12.5px;cursor:pointer} button:hover{border-color:var(--s1)}
  table{border-collapse:collapse;width:100%;font-size:12px;font-variant-numeric:tabular-nums;margin-top:8px}
  th,td{text-align:right;padding:4px 8px;border-bottom:1px solid var(--grid)} th{color:var(--secondary)}
  td:first-child,th:first-child,td:nth-child(2),th:nth-child(2){text-align:left} #tableview{display:none}
"""

_SCRIPT = """
const D=__DATA__;
const svg=document.getElementById('svg'),card=document.getElementById('card'),
  tip=document.getElementById('tip'),hl=document.getElementById('hl');
function show(i,ev){
  const it=D.items[i],b=D.bands[i];
  if(b){hl.setAttribute('y',b.y);hl.setAttribute('height',b.h);hl.style.opacity=.10;}
  tip.textContent='';
  const hd=document.createElement('b');hd.textContent=it.n&&it.n!==it.t?(it.t+' \\u00b7 '+it.n):it.t;tip.appendChild(hd);
  it.lines.forEach(function(ln){const row=document.createElement('div');
    if(ln[2]){const sw=document.createElement('s');sw.style.background='var(--'+ln[2]+')';row.appendChild(sw);}
    row.appendChild(document.createTextNode(ln[0]+'  '+ln[1]));tip.appendChild(row);});
  tip.style.opacity=1;const cr=card.getBoundingClientRect();
  tip.style.left=(ev.clientX-cr.left)+'px';tip.style.top=(ev.clientY-cr.top)+'px';
}
[...svg.querySelectorAll('.hit')].forEach(function(h){const i=+h.getAttribute('data-i');
  h.addEventListener('pointermove',function(ev){show(i,ev)});
  h.addEventListener('pointerenter',function(ev){show(i,ev)});});
svg.addEventListener('pointerleave',function(){tip.style.opacity=0;hl.style.opacity=0});
document.getElementById('tbtn').onclick=function(){const t=document.getElementById('tableview');
  t.style.display=t.style.display==='block'?'none':'block'};
document.getElementById('thm').onclick=function(){const h=document.documentElement;
  const cur=h.getAttribute('data-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');
  h.setAttribute('data-theme',cur==='dark'?'light':'dark')};
"""


def _safe_json(data: dict[str, Any]) -> str:
    """json.dumps hardened for inlining inside a <script> block."""
    return (
        json.dumps(data)
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("&", "\\u0026")
        .replace(" ", "\\u2028")
        .replace(" ", "\\u2029")
    )


def document(
    *,
    title: str,
    tab: str,
    sub: str,
    hero: list[tuple[str, str, str]],
    legend: list[tuple[str, str]],
    svg_inner: str,
    svg_h: int,
    thead: list[str],
    trows: str,
    data: dict[str, Any],
) -> str:
    """Assemble the full self-contained HTML page shared by both chart forms."""

    def cv(m: str) -> str:
        return ";".join(f"--{k}:{v}" for k, v in PAL[m].items())

    style = _STYLE.replace("__L__", cv("light")).replace("__D__", cv("dark"))
    script = _SCRIPT.replace("__DATA__", _safe_json(data))
    hero_html = "".join(
        f'<div class="metric"><span class="ml">{esc(lbl)}</span>'
        f'<span class="mv {c}">{esc(val)}</span></div>'
        for lbl, val, c in hero
    )
    leg = "".join(
        f'<span class="lg"><i style="background:var(--{r})"></i>{esc(lbl)}</span>'
        for lbl, r in legend
    )
    head = "".join(f"<th>{esc(h)}</th>" for h in thead)
    return (
        f'<!doctype html><html lang="en"><head><meta charset="utf-8">'
        f'<meta name="viewport" content="width=device-width,initial-scale=1">'
        f'<title>{esc(tab)}</title><style>{style}</style></head><body><div class="wrap">'
        f'<div class="head"><div><h1>{title}</h1><div class="sub">{esc(sub)}</div></div>'
        f'<div class="hero">{hero_html}</div></div><div class="legend">{leg}</div>'
        f'<div class="card overflow" id="card"><svg id="svg" viewBox="0 0 {W} {svg_h}" '
        f'preserveAspectRatio="xMidYMid meet" role="img" aria-label="{esc(tab)}">{svg_inner}</svg>'
        f'<div class="tip" id="tip"></div></div>'
        f'<div class="barctl"><button id="tbtn">Table view</button>'
        f'<button id="thm">Toggle light/dark</button></div>'
        f'<div id="tableview" class="overflow"><table><thead><tr>{head}</tr></thead>'
        f"<tbody>{trows}</tbody></table></div></div><script>{script}</script></body></html>"
    )
