# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Robust ETF-data provider (yfinance-backed, isolated for swap-out).

Design goals (why this exists instead of calling yfinance inline):
  - Transient failures (HTTP 429, flaky network) are retried with backoff, then
    re-raised loudly -- never swallowed into a silent None.
  - resolve() reads a value across candidate keys, so one unpopulated field
    (yfinance naming is inconsistent) does not produce a false null.
  - Expense ratio is resolved PROPERLY: .info synonyms first, then yfinance
    funds_data (fund_overview / fund_operations). Only when EVERY source is
    genuinely absent is it null, tagged 'unavailable -- see issuer factsheet'.
  - The provider is the ONLY place that imports yfinance, so a paid source
    (polygon/finnhub) can replace it without touching viz or charts.
"""

from __future__ import annotations

import math
import time
from typing import Any, Callable, Optional, TypeVar

T = TypeVar("T")

# Expense ratio lives under different keys depending on the yfinance path.
EXPENSE_KEYS = ["netExpenseRatio", "annualReportExpenseRatio", "feesExpensesInvestment"]
AUM_KEYS = ["totalAssets", "netAssets"]
NAME_KEYS = ["longName", "shortName"]
CATEGORY_KEYS = ["category", "fundFamily", "legalType", "quoteType"]


def _retry(fn: Callable[[], T], tries: int = 3, base: float = 0.6) -> T:
    last: Optional[Exception] = None
    for attempt in range(tries):
        try:
            return fn()
        except (
            Exception
        ) as exc:  # transient provider error; re-raised below if persistent
            last = exc
            time.sleep(base * (2**attempt))
    raise RuntimeError(f"ETF-data provider failed after {tries} tries: {last}")


def _as_num(v: object) -> Optional[float]:
    """A finite real number as float, else None (rejects bool, NaN, inf, strings).

    Returning Optional[float] (not a bool guard) lets the type checker narrow the
    result to a real float at each call site via a plain `is not None`.
    """
    if isinstance(v, bool) or not isinstance(v, (int, float)):
        return None
    f = float(v)
    return f if math.isfinite(f) else None


def get_info(ticker: str) -> dict[str, Any]:
    import yfinance as yf

    return _retry(lambda: dict(yf.Ticker(ticker).info or {}))


def resolve(
    info: dict[str, Any], keys: list[str]
) -> tuple[Optional[Any], Optional[str]]:
    """First populated value across candidate keys -> (value, key_used).

    Returns (None, None) only when EVERY candidate is genuinely absent -- which the
    caller should surface as 'unavailable from source', not as a zero.
    """
    for k in keys:
        v = info.get(k)
        if v is not None and v != "":
            return v, k
    return None, None


def _funds_data(ticker: str) -> Optional[object]:
    """Best-effort ETF fund block from yfinance.

    Returns None when the symbol is not a fund, or the installed yfinance lacks
    funds_data. An absent fund block is a real 'no data', not a transient error,
    so it is intentionally NOT retried or raised here -- the caller falls back.
    """
    import yfinance as yf

    t = yf.Ticker(ticker)
    try:
        fd = getattr(t, "funds_data", None)
        if fd is None and hasattr(t, "get_funds_data"):
            fd = t.get_funds_data()
        return fd
    except Exception:  # intentional best-effort: not every ticker exposes funds_data
        return None


def _as_dict(obj: object) -> dict[str, Any]:
    """Coerce a funds_data.fund_overview (dict-like) into a plain dict."""
    if isinstance(obj, dict):
        return {str(k): v for k, v in obj.items()}
    items = getattr(obj, "items", None)
    if callable(items):
        try:
            pairs: Any = (
                items()
            )  # Any at the external-shape boundary (unknown iterable)
            return {str(k): v for k, v in pairs}
        except Exception:  # intentional best-effort: shape varies across versions
            return {}
    return {}


def _expense_from_operations(fd: object) -> Optional[float]:
    """Read the net expense-ratio row from funds_data.fund_operations.

    fund_operations is a DataFrame whose row index carries metric labels and whose
    columns carry per-ticker values. Duck-typed so pandas is not a hard dependency
    of this module; any shape surprise degrades to None (best-effort).
    """
    ops = getattr(fd, "fund_operations", None)
    if ops is None:
        return None
    try:
        for label in list(getattr(ops, "index", [])):
            if "expense ratio" in str(label).lower():
                row = ops.loc[label]
                for cell in list(row):
                    num = _as_num(cell)
                    if num is not None:
                        return num
        return None
    except Exception:  # intentional best-effort: funds_data shape varies by version
        return None


def _normalize_ratio(v: float) -> float:
    """Return an expense ratio as a decimal fraction (0.0020 == 0.20%).

    yfinance .info reports a fraction (0.0020); funds_data.fund_operations often
    reports a percent (0.20). Expense ratios are never >= ~5%, so a value above 1
    is unambiguously already in percent units and is divided back to a fraction.
    """
    return v / 100.0 if v > 1.0 else v


def get_expense_ratio(ticker: str, info: dict[str, Any]) -> tuple[Optional[float], str]:
    """Expense ratio as a decimal fraction, plus the source it came from.

    Order: (1) .info synonyms, (2) funds_data.fund_overview, (3)
    funds_data.fund_operations. Only when all are absent is (None, 'unavailable
    -- see issuer factsheet') returned. Never a silent null, never a hardcoded guess.
    """
    val, key = resolve(info, EXPENSE_KEYS)
    num = _as_num(val)
    if num is not None:
        return _normalize_ratio(num), str(key)

    fd = _funds_data(ticker)
    if fd is not None:
        overview = _as_dict(getattr(fd, "fund_overview", None))
        v2, k2 = resolve(overview, EXPENSE_KEYS)
        num2 = _as_num(v2)
        if num2 is not None:
            return _normalize_ratio(num2), f"funds_data.fund_overview:{k2}"
        v3 = _expense_from_operations(fd)
        if v3 is not None:
            return _normalize_ratio(v3), "funds_data.fund_operations"

    return None, "unavailable -- see issuer factsheet"


def _holdings_from_info(info: dict[str, Any]) -> list[dict[str, Any]]:
    raw = info.get("holdings")
    rows: list[dict[str, Any]] = []
    if isinstance(raw, list):
        for h in raw:
            if not isinstance(h, dict):
                continue
            sym = str(h.get("symbol") or "")
            weight = _as_num(h.get("holdingPercent"))
            if weight is not None:
                rows.append(
                    {
                        "symbol": sym,
                        "name": str(h.get("holdingName") or sym),
                        "weight": weight,
                    }
                )
    return rows


def _holdings_from_funds_data(ticker: str) -> list[dict[str, Any]]:
    """Best-effort top holdings from funds_data.top_holdings (a DataFrame)."""
    fd = _funds_data(ticker)
    if fd is None:
        return []
    th = getattr(fd, "top_holdings", None)
    if th is None:
        return []
    try:
        cols = [str(c) for c in getattr(th, "columns", [])]
        pct_col = next((c for c in cols if "percent" in c.lower()), None)
        name_col = next((c for c in cols if "name" in c.lower()), None)
        rows: list[dict[str, Any]] = []
        for sym, row in th.iterrows():
            weight = _as_num(row[pct_col]) if pct_col is not None else None
            if weight is None:
                continue
            name = row[name_col] if name_col is not None else sym
            rows.append(
                {
                    "symbol": str(sym),
                    "name": str(name),
                    "weight": weight,
                }
            )
        return rows
    except Exception:  # intentional best-effort: funds_data shape varies by version
        return []


def get_holdings(ticker: str, info: dict[str, Any]) -> list[dict[str, Any]]:
    """Top holdings [{symbol, name, weight(fraction)}], largest weight first.

    Returns [] when the issuer has not disclosed constituents (a real absence the
    caller should surface with an as-of note, not a fabricated list).
    """
    rows = _holdings_from_info(info)
    if not rows:
        rows = _holdings_from_funds_data(ticker)
    rows.sort(key=lambda r: float(r["weight"]), reverse=True)
    return rows


def get_etf_profile(ticker: str) -> dict[str, Any]:
    """Full ETF snapshot: name, category, expense ratio (+ source), AUM, holdings."""
    info = get_info(ticker)
    expense_ratio, expense_source = get_expense_ratio(ticker, info)
    aum_raw, _ = resolve(info, AUM_KEYS)
    aum = _as_num(aum_raw)
    name, _ = resolve(info, NAME_KEYS)
    category, _ = resolve(info, CATEGORY_KEYS)
    return {
        "ticker": ticker.upper(),
        "name": str(name) if name else ticker.upper(),
        "category": str(category) if category else None,
        "expense_ratio": expense_ratio,
        "expense_ratio_source": expense_source,
        "aum": int(aum) if aum is not None else None,
        "holdings": get_holdings(ticker, info),
    }


def holdings_overlap(
    a: list[dict[str, Any]], b: list[dict[str, Any]]
) -> dict[str, Any]:
    """Weight-based overlap between two ETFs' holdings.

        overlap_pct = sum( min(weight_A[i], weight_B[i]) ) over shared symbols

    Weights are the decimal fractions from get_holdings; overlap_pct is returned
    as a percentage (0-100). shared rows carry both weights for a grouped chart.
    """
    wa = {str(h["symbol"]): float(h["weight"]) for h in a if h.get("symbol")}
    wb = {str(h["symbol"]): float(h["weight"]) for h in b if h.get("symbol")}
    names: dict[str, str] = {}
    for h in a + b:
        sym = str(h.get("symbol") or "")
        if sym and sym not in names:
            names[sym] = str(h.get("name") or sym)
    shared_syms = sorted(
        set(wa) & set(wb), key=lambda s: min(wa[s], wb[s]), reverse=True
    )
    overlap = sum(min(wa[s], wb[s]) for s in shared_syms) * 100.0
    shared = [
        {
            "symbol": s,
            "name": names.get(s, s),
            "weight_a": wa[s],
            "weight_b": wb[s],
        }
        for s in shared_syms
    ]
    return {
        "overlap_pct": round(overlap, 2),
        "shared_count": len(shared_syms),
        "shared": shared,
    }


if __name__ == "__main__":  # tiny self-test of the pure overlap math (no network)
    import json

    def _row(sym: str, w: float) -> dict[str, Any]:
        return {"symbol": sym, "name": sym, "weight": w}

    demo_a = [_row("AAPL", 0.07), _row("MSFT", 0.06), _row("NVDA", 0.05)]
    demo_b = [_row("AAPL", 0.06), _row("MSFT", 0.06), _row("TSLA", 0.03)]
    print(json.dumps(holdings_overlap(demo_a, demo_b), indent=2))
