# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Self-contained interactive HTML/SVG ETF composition chart (no third-party deps).

Renders an ETF's top holdings as horizontal bars (sequential single-hue blue ramp
-- darkest = largest weight) with an expense-ratio + AUM readout, into one HTML
file: inline SVG, hover highlight + tooltip, table view, light/dark toggle. With
--compare it groups two ETFs' shared holdings side by side (categorical two-colour)
and reports overlap % and the expense delta.

The page shell (the exact data-viz reference PALETTE, CSS, JS, and the XSS-safe
page assembler) lives in htmlshell.py and is reused here; this module only builds
the SVG marks. OPTIONAL layer: rendered only when a chart helps or is asked for.
"""

from __future__ import annotations

from typing import Any

from htmlshell import ML, MR, MT, W, PAL, document, esc, money, nice_max, pct

__all__ = ["render_holdings_chart", "render_overlap_chart", "PAL"]


def _plot(
    rows: list[dict[str, Any]], axis_max: float, row_h: int, gap: int
) -> tuple[str, int, list[dict[str, Any]], list[dict[str, Any]]]:
    """Shared bar SVG from generic row specs -> (svg, height, items, bands).

    Each row: {lab, name, lines, segs:[{v,fill,op,h,dy,val}]}; v is a percent and
    segs are the coloured bars stacked inside the row band. Recessive grid + axis;
    direct row/value labels; one transparent hit-rect per row drives the tooltip.
    """
    px0, px1 = ML, W - MR
    n = len(rows)
    bottom = MT + n * row_h + (n - 1) * gap
    grid, xlab = [], []
    for i in range(5):
        v = axis_max * i / 4
        x = px0 + (v / axis_max) * (px1 - px0)
        grid.append(
            f'<line x1="{x:.1f}" y1="{MT}" x2="{x:.1f}" y2="{bottom:.1f}" class="grid"/>'
        )
        xlab.append(
            f'<text x="{x:.1f}" y="{bottom + 20:.1f}" class="xtick">{v:.1f}%</text>'
        )
    base = f'<line x1="{px0}" y1="{bottom:.1f}" x2="{px1}" y2="{bottom:.1f}" class="axis"/>'
    bars, labels, hits, items, bands = [], [], [], [], []
    for k, r in enumerate(rows):
        y = MT + k * (row_h + gap)
        for seg in r["segs"]:
            length = (seg["v"] / axis_max) * (px1 - px0)
            sy = y + seg["dy"]
            bars.append(
                f'<rect class="bar" x="{px0}" y="{sy:.1f}" width="{max(length, 0.5):.1f}" '
                f'height="{seg["h"]}" rx="2" fill="{seg["fill"]}" fill-opacity="{seg["op"]:.3f}"/>'
            )
            labels.append(
                f'<text x="{px0 + length + 5:.1f}" y="{sy + seg["h"] / 2 + 3.5:.1f}" '
                f'class="barval">{seg["val"]}</text>'
            )
        labels.append(
            f'<text x="{px0 - 8}" y="{y + row_h / 2 + 4:.1f}" class="rowlab">{esc(r["lab"])}</text>'
        )
        hits.append(
            f'<rect class="hit" x="{px0}" y="{y:.1f}" width="{px1 - px0:.1f}" '
            f'height="{row_h}" data-i="{k}"/>'
        )
        items.append({"t": r["lab"], "n": r["name"], "lines": r["lines"]})
        bands.append({"y": round(y, 1), "h": row_h})
    hl = f'<rect id="hl" x="{px0}" width="{px1 - px0:.1f}" height="0"/>'
    svg = (
        "".join(grid)
        + base
        + "".join(bars)
        + "".join(labels)
        + "".join(xlab)
        + hl
        + "".join(hits)
    )
    return svg, int(bottom + 44), items, bands


def _note(msg: str) -> tuple[str, int]:
    svg = (
        f'<rect id="hl" x="{ML}" width="{W - ML - MR}" height="0"/>'
        f'<text x="{ML}" y="{MT + 40}" class="note">{esc(msg)}</text>'
    )
    return svg, MT + 90


def render_holdings_chart(profile: dict[str, Any], as_of: str, top: int = 15) -> str:
    """Single-ETF top-holdings composition (sequential blue ramp) + cost readout."""
    ticker = str(profile.get("ticker") or "")
    name = str(profile.get("name") or "")
    holdings = list(profile.get("holdings") or [])[:top]
    expense = profile.get("expense_ratio")
    epct = float(expense) * 100 if expense is not None else None
    esrc = str(profile.get("expense_ratio_source") or "")
    weights = [float(h["weight"]) * 100 for h in holdings]
    hero = [
        ("Expense ratio", pct(epct), "" if epct is not None else "muted"),
        ("AUM", money(profile.get("aum")), "muted"),
        ("Top-10 wt.", pct(sum(weights[:10]), 1) if weights else "n/a", "muted"),
    ]
    sub = (
        f"Top {len(holdings)} holdings by weight · expense source: "
        f"{esrc or 'n/a'} · as of {as_of}"
    )
    title = f"{esc(ticker)} · {esc(name or ticker)}"
    thead = ["#", "Symbol", "Name", "Weight"]
    if not holdings:
        svg, h = _note(
            "No constituent disclosure available -- issuers disclose on a delay; "
            "check the issuer factsheet for the latest as-of date."
        )
        return document(
            title=title,
            tab=f"{ticker} holdings",
            sub=sub,
            hero=hero,
            legend=[],
            svg_inner=svg,
            svg_h=h,
            thead=thead,
            trows="",
            data={"items": [], "bands": []},
        )
    n = len(holdings)
    axis_max = nice_max(max(weights))
    rows: list[dict[str, Any]] = []
    for k, hd in enumerate(holdings):
        w = weights[k]
        op = 1.0 if n == 1 else 0.42 + 0.58 * (1 - k / (n - 1))
        rows.append(
            {
                "lab": str(hd.get("symbol") or "?"),
                "name": str(hd.get("name") or hd.get("symbol") or "?"),
                "lines": [["Weight", f"{w:.2f}%"]],
                "segs": [
                    {
                        "v": w,
                        "fill": "var(--s1)",
                        "op": op,
                        "h": 22,
                        "dy": 0,
                        "val": f"{w:.2f}%",
                    }
                ],
            }
        )
    svg, h, items, bands = _plot(rows, axis_max, 22, 10)
    trows = "".join(
        f"<tr><td>{k + 1}</td><td>{esc(hd.get('symbol') or '?')}</td>"
        f"<td>{esc(hd.get('name') or '')}</td><td>{weights[k]:.2f}%</td></tr>"
        for k, hd in enumerate(holdings)
    )
    return document(
        title=title,
        tab=f"{ticker} holdings composition",
        sub=sub,
        hero=hero,
        legend=[],
        svg_inner=svg,
        svg_h=h,
        thead=thead,
        trows=trows,
        data={"items": items, "bands": bands},
    )


def render_overlap_chart(
    a: dict[str, Any],
    b: dict[str, Any],
    overlap: dict[str, Any],
    as_of: str,
    top: int = 15,
) -> str:
    """Two-ETF grouped bars over shared/top holdings + overlap % and cost delta."""
    ta, tb = str(a.get("ticker") or "A"), str(b.get("ticker") or "B")
    wa = {str(h["symbol"]): float(h["weight"]) * 100 for h in (a.get("holdings") or [])}
    wb = {str(h["symbol"]): float(h["weight"]) * 100 for h in (b.get("holdings") or [])}
    names: dict[str, str] = {}
    for h in (a.get("holdings") or []) + (b.get("holdings") or []):
        s = str(h.get("symbol") or "")
        if s and s not in names:
            names[s] = str(h.get("name") or s)
    union = sorted(
        set(wa) | set(wb),
        key=lambda s: max(wa.get(s, 0.0), wb.get(s, 0.0)),
        reverse=True,
    )[:top]
    ea, eb = a.get("expense_ratio"), b.get("expense_ratio")
    eap = float(ea) * 100 if ea is not None else None
    ebp = float(eb) * 100 if eb is not None else None
    delta = eap - ebp if (eap is not None and ebp is not None) else None
    # Lower cost is better -> green when A is cheaper, red when A is pricier.
    dcls = (
        ""
        if delta is None
        else ("up" if delta < 0 else "down" if delta > 0 else "muted")
    )
    dtxt = (
        "n/a"
        if delta is None
        else f"{'+' if delta > 0 else ''}{delta:.2f} pp ({ta} vs {tb})"
    )
    hero = [
        ("Weight overlap", pct(float(overlap.get("overlap_pct") or 0.0), 1), ""),
        ("Expense delta", dtxt, dcls),
    ]
    sub = (
        f"{ta} vs {tb} · shared holdings: {overlap.get('shared_count', 0)} · "
        f"{ta} {pct(eap)} / {tb} {pct(ebp)} · as of {as_of}"
    )
    title = f"{esc(ta)} · {esc(tb)} overlap"
    legend = [(ta, "s1"), (tb, "s2")]
    thead = ["Symbol", "Name", f"{ta} wt.", f"{tb} wt."]
    if not union:
        svg, h = _note("No overlapping constituent disclosure available for this pair.")
        return document(
            title=title,
            tab=f"{ta} vs {tb} overlap",
            sub=sub,
            hero=hero,
            legend=legend,
            svg_inner=svg,
            svg_h=h,
            thead=thead,
            trows="",
            data={"items": [], "bands": []},
        )
    axis_max = nice_max(max(max(wa.get(s, 0.0), wb.get(s, 0.0)) for s in union))
    rows: list[dict[str, Any]] = []
    for s in union:
        va, vb = wa.get(s, 0.0), wb.get(s, 0.0)
        rows.append(
            {
                "lab": s,
                "name": names.get(s, s),
                "lines": [[ta, f"{va:.2f}%", "s1"], [tb, f"{vb:.2f}%", "s2"]],
                "segs": [
                    {
                        "v": va,
                        "fill": "var(--s1)",
                        "op": 1.0,
                        "h": 12,
                        "dy": 0,
                        "val": f"{va:.1f}",
                    },
                    {
                        "v": vb,
                        "fill": "var(--s2)",
                        "op": 1.0,
                        "h": 12,
                        "dy": 15,
                        "val": f"{vb:.1f}",
                    },
                ],
            }
        )
    svg, h, items, bands = _plot(rows, axis_max, 27, 12)
    trows = "".join(
        f"<tr><td>{esc(s)}</td><td>{esc(names.get(s, s))}</td>"
        f"<td>{wa.get(s, 0.0):.2f}%</td><td>{wb.get(s, 0.0):.2f}%</td></tr>"
        for s in union
    )
    return document(
        title=title,
        tab=f"{ta} vs {tb} holdings overlap",
        sub=sub,
        hero=hero,
        legend=legend,
        svg_inner=svg,
        svg_h=h,
        thead=thead,
        trows=trows,
        data={"items": items, "bands": bands},
    )
