# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Render an interactive diverging-bar chart of dual-listed gap % per pair.

OPTIONAL visualization step -- run it only when a chart helps the answer or the
user asks to see/visualize the gaps. The text analysis never depends on it.

Pipeline: provider (robust US + ".TA" fetch, USD/ILS rate) -> gap math ->
viz.render_gap_chart (self-contained interactive HTML). A pair whose Tel-Aviv
leg or price is unavailable from the free source is reported as skipped, never
fabricated. If the FX rate cannot be fetched and no --boi-rate is supplied, no
gap can be computed and the run exits with guidance rather than inventing a rate.

Usage:
    python scripts/chart.py --pairs CHKP,NICE,TEVA --out gaps.html
    python scripts/chart.py --pairs CHKP,NICE --boi-rate 3.65 --out gaps.html
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import provider
import viz

DEFAULT_THRESHOLD = 2.0


def compute_pair(
    symbol: str, fx: float, adr: float, threshold: float
) -> tuple[viz.PairGap, str]:
    """Fetch both legs and derive the currency-adjusted gap.

    Returns (pair-gap, as-of date). Raises if either leg is missing so the
    caller can skip the pair honestly instead of guessing a price.
    """
    us_usd, us_date = provider.get_us_leg(symbol)
    tase_ils, tase_date, _currency = provider.get_tase_leg(symbol)
    us_in_ils = us_usd * fx * adr
    gap_pct = (tase_ils - us_in_ils) / us_in_ils * 100.0 if us_in_ils else 0.0
    pair = viz.PairGap(
        pair=symbol,
        gap_pct=round(gap_pct, 2),
        tase_ils=round(tase_ils, 2),
        us_in_ils=round(us_in_ils, 2),
        us_usd=round(us_usd, 2),
        flagged=abs(gap_pct) > threshold,
    )
    return pair, max(us_date, tase_date)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Interactive dual-listed gap chart (diverging bars, HTML)."
    )
    ap.add_argument(
        "--pairs",
        required=True,
        help="comma-separated TASE symbols, e.g. CHKP,NICE,TEVA",
    )
    ap.add_argument(
        "--boi-rate",
        type=float,
        default=None,
        help="USD/ILS representative rate; omit to fetch USDILS=X live",
    )
    ap.add_argument("--adr", type=float, default=1.0, help="US shares per TASE share")
    ap.add_argument(
        "--threshold",
        type=float,
        default=DEFAULT_THRESHOLD,
        help="abs(gap%%) that flags a pair (default 2.0)",
    )
    ap.add_argument("--out", default="dual-listed-gaps.html")
    a = ap.parse_args()

    symbols = [s.strip().upper() for s in a.pairs.split(",") if s.strip()]
    if not symbols:
        print("no pairs given", file=sys.stderr)
        return 2

    try:
        fx, fx_label = provider.get_fx_usdils(a.boi_rate)
    except Exception as exc:  # FX is shared: without it NO gap can be computed
        print(
            f"USD/ILS rate unavailable ({exc}); pass --boi-rate to proceed",
            file=sys.stderr,
        )
        return 1

    pairs: list[viz.PairGap] = []
    unavailable: list[viz.Unavailable] = []
    dates: list[str] = []
    for sym in symbols:
        try:
            pair, as_of = compute_pair(sym, fx, a.adr, a.threshold)
            pairs.append(pair)
            dates.append(as_of)
        except Exception as exc:  # per-pair: skip honestly, never fabricate
            unavailable.append(viz.Unavailable(pair=sym, reason=str(exc)[:120]))

    if not pairs:
        print("no pair had both legs available; nothing to chart", file=sys.stderr)
        for u in unavailable:
            print(f"  {u.pair}: {u.reason}", file=sys.stderr)
        return 1

    as_of = max(dates)
    doc = viz.render_gap_chart(pairs, unavailable, fx, fx_label, a.threshold, as_of)
    Path(a.out).write_text(doc, encoding="utf-8")
    print(
        f"wrote {a.out} ({len(doc)} bytes, {len(pairs)} pairs charted, "
        f"{len(unavailable)} unavailable, as of {as_of})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
