# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Robust dual-listing data provider (yfinance-backed, isolated for swap-out).

Fetches the US leg live and attempts the Tel-Aviv (".TA") leg of the same
company, plus a USD/ILS rate, so a caller can compute the cross-listing gap.

Design goals (why this exists instead of calling yfinance inline):
  - Transient failures (HTTP 429, flaky network) are retried with backoff, then
    re-raised loudly -- never swallowed into a silent None. The ORCHESTRATOR
    decides, per pair, whether a raised failure means "skip this pair"; the
    provider itself never fabricates a fallback price or rate.
  - resolve() reads a value across several candidate keys, so one unpopulated
    field (yfinance is inconsistent about naming) does not produce a false null
    when a synonym carries the value.
  - The provider is the ONLY place that imports yfinance, so a paid source
    (polygon/finnhub) or the Bank of Israel FX feed can replace it without
    touching the chart or the gap math.
"""

from __future__ import annotations

import time
from typing import Any, Callable, Optional, TypeVar

T = TypeVar("T")


def _retry(fn: Callable[[], T], tries: int = 3, base: float = 0.6) -> T:
    last: Optional[Exception] = None
    for attempt in range(tries):
        try:
            return fn()
        except (
            Exception
        ) as exc:  # transient provider error; re-raised below if persistent
            last = exc
            time.sleep(base * (2**attempt))
    raise RuntimeError(f"market-data provider failed after {tries} tries: {last}")


def get_history(
    ticker: str, period: str = "5d", interval: str = "1d"
) -> list[dict[str, Any]]:
    """Close rows, oldest -> newest. Raises if the ticker has no data."""
    import yfinance as yf

    def _pull() -> Any:
        h = yf.Ticker(ticker).history(period=period, interval=interval)
        if h.empty:
            raise ValueError(
                f"no market data for {ticker!r} (check the symbol/exchange)"
            )
        return h

    hist = _retry(_pull)
    rows: list[dict[str, Any]] = []
    for idx, row in hist.iterrows():
        rows.append(
            {
                "date": idx.strftime("%Y-%m-%d"),
                "close": round(float(row["Close"]), 4),
            }
        )
    return rows


def get_info(ticker: str) -> dict[str, Any]:
    import yfinance as yf

    return _retry(lambda: dict(yf.Ticker(ticker).info or {}))


def resolve(
    info: dict[str, Any], keys: list[str]
) -> tuple[Optional[Any], Optional[str]]:
    """First populated value across candidate keys -> (value, key_used).

    Returns (None, None) only when EVERY candidate is genuinely absent -- which
    the caller should surface as 'unavailable from source', not as a zero.
    """
    for k in keys:
        v = info.get(k)
        if v is not None and v != "":
            return v, k
    return None, None


def get_last_close(ticker: str) -> tuple[float, str]:
    """(last FINITE close, as-of date) for one line.

    Yahoo emits a trailing NaN row for TASE lines while the exchange is closed
    (pre-open placeholder). Walk back to the last finite close instead of
    trusting rows[-1]; raise if the whole window is NaN -- the caller skips the
    pair honestly rather than charting NaN.
    """
    import math

    rows = get_history(ticker)
    for row in reversed(rows):
        px = float(row["close"])
        if math.isfinite(px):
            return px, str(row["date"])
    raise ValueError(f"no finite close for {ticker!r} in the returned window")


def get_us_leg(us_ticker: str) -> tuple[float, str]:
    """US price in USD + as-of date. Raises on no data (the pair is unusable)."""
    return get_last_close(us_ticker)


def get_tase_leg(tase_symbol: str) -> tuple[float, str, str]:
    """(price in ILS, as-of date, currency tag) for the Tel-Aviv leg.

    Appends the ".TA" suffix. TASE equities quote in agorot; we convert to
    shekels by dividing by 100 UNLESS yfinance reports the line already in ILS.
    Raises if the ".TA" line has no data -- the caller then skips that pair
    rather than guessing a price.
    """
    ta_ticker = tase_symbol if tase_symbol.endswith(".TA") else f"{tase_symbol}.TA"
    raw, as_of = get_last_close(ta_ticker)
    currency = "ILA"  # documented TASE default (agorot) when info is unavailable
    try:  # best-effort: confirm the quote currency so the 100x scale is correct
        cur, _ = resolve(get_info(ta_ticker), ["currency"])
        if cur:
            currency = str(cur).upper()
    except Exception:  # best-effort only: fall back to the agorot default
        currency = "ILA"
    price_ils = raw if currency == "ILS" else raw / 100.0
    return round(price_ils, 4), as_of, currency


def get_fx_usdils(boi_rate: Optional[float]) -> tuple[float, str]:
    """USD/ILS rate. Prefers an explicit representative rate; else 'USDILS=X'.

    Raises if no rate can be obtained and none was supplied -- the caller must
    surface that (and ask for --boi-rate) rather than invent a rate.
    """
    if boi_rate is not None:
        return float(boi_rate), "representative rate (supplied)"
    rate, _ = get_last_close("USDILS=X")
    return float(rate), "USDILS=X (yfinance)"
