# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Render an interactive HTML price + RSI chart for a US/global ticker.

OPTIONAL visualization step -- run it only when a chart helps the answer or the
user asks to see/visualize. The text analysis never depends on it.

Pipeline: provider.get_history (robust fetch) -> indicators (pure Python) ->
viz.render_price_chart (self-contained interactive HTML).

Usage:
    python scripts/chart.py --ticker AAPL --period 6mo --out AAPL.html
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import indicators
import provider
import viz


def main() -> int:
    ap = argparse.ArgumentParser(description="Interactive price+RSI chart (HTML).")
    ap.add_argument("--ticker", required=True)
    ap.add_argument(
        "--period", default="1y", help="1y+ so EMA200 has enough history to render"
    )
    ap.add_argument("--name", default="")
    ap.add_argument("--out", default="")
    a = ap.parse_args()

    rows = provider.get_history(a.ticker, a.period)
    dates = [r["date"] for r in rows]
    closes = [r["close"] for r in rows]
    emas = {
        "EMA20": indicators.ema(closes, 20),
        "EMA50": indicators.ema(closes, 50),
        "EMA200": indicators.ema(closes, 200),
    }
    rsi = indicators.rsi(closes, 14)

    name = a.name
    if not name:
        try:
            name = str(provider.get_info(a.ticker).get("shortName") or a.ticker)
        except Exception:  # silent: best-effort -- name is cosmetic, symbol is fine
            name = a.ticker

    doc = viz.render_price_chart(a.ticker, name, dates, closes, emas, rsi, dates[-1])
    out = a.out or f"{a.ticker}.html"
    Path(out).write_text(doc)
    print(f"wrote {out} ({len(doc)} bytes, {len(rows)} rows, last {dates[-1]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
