# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Robust market-data provider (yfinance-backed, isolated for swap-out).

Design goals (why this exists instead of calling yfinance inline):
  - Transient failures (HTTP 429, flaky network) are retried with backoff, then
    re-raised loudly -- never swallowed into a silent None.
  - resolve() reads a value across several candidate keys, so one unpopulated
    field (yfinance is inconsistent about naming) does not produce a false null
    when a synonym carries the value.
  - The provider is the ONLY place that imports yfinance, so a paid source
    (polygon/finnhub) can replace it without touching indicators or charts.
"""

from __future__ import annotations

import math
import time
from typing import Any, Callable, Optional, TypeVar

T = TypeVar("T")


def _retry(fn: Callable[[], T], tries: int = 3, base: float = 0.6) -> T:
    last: Optional[Exception] = None
    for attempt in range(tries):
        try:
            return fn()
        except (
            Exception
        ) as exc:  # transient provider error; re-raised below if persistent
            last = exc
            time.sleep(base * (2**attempt))
    raise RuntimeError(f"market-data provider failed after {tries} tries: {last}")


def get_history(
    ticker: str, period: str = "6mo", interval: str = "1d"
) -> list[dict[str, Any]]:
    """OHLCV rows, oldest -> newest. Raises if the ticker has no data."""
    import yfinance as yf

    def _pull():
        h = yf.Ticker(ticker).history(period=period, interval=interval)
        if h.empty:
            raise ValueError(
                f"no market data for {ticker!r} (check the symbol/exchange)"
            )
        return h

    hist = _retry(_pull)
    rows: list[dict[str, Any]] = []
    for idx, row in hist.iterrows():
        px = float(row["Close"])
        if not math.isfinite(px):
            # Yahoo emits NaN placeholder rows (e.g. pre-open); a NaN close would
            # poison every indicator downstream, so drop the row at the boundary.
            continue
        rows.append(
            {
                "date": idx.strftime("%Y-%m-%d"),
                "open": round(float(row["Open"]), 4),
                "high": round(float(row["High"]), 4),
                "low": round(float(row["Low"]), 4),
                "close": round(px, 4),
                "volume": int(row["Volume"]),
            }
        )
    if not rows:
        raise ValueError(f"only NaN closes for {ticker!r} in the returned window")
    return rows


def get_info(ticker: str) -> dict[str, Any]:
    import yfinance as yf

    return _retry(lambda: dict(yf.Ticker(ticker).info or {}))


def resolve(
    info: dict[str, Any], keys: list[str]
) -> tuple[Optional[Any], Optional[str]]:
    """First populated value across candidate keys -> (value, key_used).

    Returns (None, None) only when EVERY candidate is genuinely absent -- which the
    caller should surface as 'unavailable from source', not as a zero.
    """
    for k in keys:
        v = info.get(k)
        if v is not None and v != "":
            return v, k
    return None, None
