# Generated by OrchestKit Claude Plugin
# Created: 2026-07-02

#!/usr/bin/env python3
"""Self-contained interactive HTML/SVG chart generator (no third-party deps).

Renders a stock price panel (close + EMA overlays) and an RSI sub-panel into a
single HTML file: inline SVG, hover crosshair + tooltip, a table view, and a
light/dark toggle. Colours come from the data-viz reference palette, which is
already colour-blind validated (worst adjacent CVD dE 24.2, light).

This is the OPTIONAL visualization layer -- the skill renders it only when a
chart helps or the user asks; the text answer never depends on it.
"""

from __future__ import annotations

import html
import json
from typing import Optional

# Data-viz reference palette (roles only; light + dark are both selected sets).
PAL = {
    "light": {
        "surface": "#fcfcfb",
        "page": "#f9f9f7",
        "primary": "#0b0b0b",
        "secondary": "#52514e",
        "muted": "#898781",
        "grid": "#e1e0d9",
        "axis": "#c3c2b7",
        "s1": "#2a78d6",
        "s2": "#1baf7a",
        "s3": "#eda100",
        "s4": "#4a3aa7",
        "good": "#006300",
        "bad": "#d03b3b",
        "bandfill": "#e1e0d9",
    },
    "dark": {
        "surface": "#1a1a19",
        "page": "#0d0d0d",
        "primary": "#ffffff",
        "secondary": "#c3c2b7",
        "muted": "#898781",
        "grid": "#2c2c2a",
        "axis": "#383835",
        "s1": "#3987e5",
        "s2": "#199e70",
        "s3": "#c98500",
        "s4": "#9085e9",
        "good": "#0ca30c",
        "bad": "#d03b3b",
        "bandfill": "#2c2c2a",
    },
}
SERIES = [("Close", "s1"), ("EMA20", "s2"), ("EMA50", "s3"), ("EMA200", "s4")]

W, MT, MB, ML, MR = 960, 16, 28, 60, 78
PH, RH, GAP = 360, 120, 34  # price panel, rsi panel, gap
H = MT + PH + GAP + RH + MB
PX0, PX1 = ML, W - MR  # plot x span
PY0, PY1 = MT, MT + PH  # price panel y span
RY0, RY1 = MT + PH + GAP, MT + PH + GAP + RH


def _xs(n: int) -> list[float]:
    if n <= 1:
        return [PX0 for _ in range(n)]
    return [PX0 + i * (PX1 - PX0) / (n - 1) for i in range(n)]


def _path(xs: list[float], ys: list[Optional[float]], y_of) -> str:
    d, pen = [], False
    for x, y in zip(xs, ys):
        if y is None:
            pen = False
            continue
        cmd = "M" if not pen else "L"
        d.append(f"{cmd}{x:.1f} {y_of(y):.1f}")
        pen = True
    return " ".join(d)


def _fmt(v: Optional[float], nd: int = 2) -> str:
    return "-" if v is None else f"{v:,.{nd}f}"


def render_price_chart(
    ticker: str,
    name: str,
    dates: list[str],
    closes: list[float],
    emas: dict[str, list[Optional[float]]],
    rsi: list[Optional[float]],
    as_of: str,
) -> str:
    n = len(closes)
    xs = _xs(n)
    lines = [
        closes,
        emas.get("EMA20", [None] * n),
        emas.get("EMA50", [None] * n),
        emas.get("EMA200", [None] * n),
    ]

    # price scale from every defined value across all price-panel series
    pvals = [v for L in lines for v in L if v is not None]
    pmin, pmax = min(pvals), max(pvals)
    pad = (pmax - pmin) * 0.06 or 1.0
    pmin, pmax = pmin - pad, pmax + pad

    def py(v: float) -> float:
        return PY1 - (v - pmin) / (pmax - pmin) * (PY1 - PY0)

    def ry(v: float) -> float:
        return RY1 - (v / 100.0) * (RY1 - RY0)

    # gridlines + y labels (price)
    grid, ylab = [], []
    for t in range(5):
        v = pmin + (pmax - pmin) * t / 4
        y = py(v)
        grid.append(
            f'<line x1="{PX0}" y1="{y:.1f}" x2="{PX1}" y2="{y:.1f}" class="grid"/>'
        )
        ylab.append(
            f'<text x="{PX0 - 8}" y="{y + 3:.1f}" class="ytick">{_fmt(v)}</text>'
        )
    # x labels (~6 evenly spaced dates)
    xlab = []
    step = max(1, n // 6)
    for i in range(0, n, step):
        xlab.append(
            f'<text x="{xs[i]:.1f}" y="{RY1 + 18}" class="xtick">{html.escape(dates[i][5:])}</text>'
        )

    # series paths + direct end-labels
    paths, endlabels, legend = [], [], []
    for (label, role), L in zip(SERIES, lines):
        paths.append(
            f'<path d="{_path(xs, L, py)}" fill="none" stroke="var(--{role})" '
            f'stroke-width="2" stroke-linejoin="round" stroke-linecap="round"/>'
        )
        last = next((v for v in reversed(L) if v is not None), None)
        if last is not None:
            endlabels.append(
                f'<text x="{PX1 + 6}" y="{py(last) + 3:.1f}" class="endlab" '
                f'style="fill:var(--{role})">{label}</text>'
            )
        legend.append(
            f'<span class="lg"><i style="background:var(--{role})"></i>{label}</span>'
        )

    # RSI panel: 30/70 band + line
    rband = (
        f'<rect x="{PX0}" y="{ry(70):.1f}" width="{PX1 - PX0:.1f}" height="{ry(30) - ry(70):.1f}" '
        f'class="rsiband"/>'
    )
    rlines = "".join(
        f'<line x1="{PX0}" y1="{ry(v):.1f}" x2="{PX1}" y2="{ry(v):.1f}" class="rsiline"/>'
        f'<text x="{PX0 - 8}" y="{ry(v) + 3:.1f}" class="ytick">{v}</text>'
        for v in (30, 70)
    )
    rpath = f'<path d="{_path(xs, rsi, ry)}" fill="none" stroke="var(--s1)" stroke-width="2"/>'

    # hero: last close + period delta
    last_close = closes[-1]
    delta = (last_close - closes[0]) / closes[0] * 100 if closes[0] else 0.0
    dcls = "up" if delta >= 0 else "down"
    last_rsi = next((v for v in reversed(rsi) if v is not None), None)

    # embedded data for the hover layer
    data = {
        "xs": [round(x, 1) for x in xs],
        "dates": dates,
        "rows": [
            [
                _fmt(closes[i]),
                _fmt(lines[1][i]),
                _fmt(lines[2][i]),
                _fmt(lines[3][i]),
                _fmt(rsi[i], 1),
            ]
            for i in range(n)
        ],
    }

    # table view
    trows = "".join(
        f"<tr><td>{html.escape(dates[i])}</td><td>{_fmt(closes[i])}</td><td>{_fmt(lines[1][i])}</td>"
        f"<td>{_fmt(lines[2][i])}</td><td>{_fmt(lines[3][i])}</td><td>{_fmt(rsi[i], 1)}</td></tr>"
        for i in range(n - 1, -1, -1)
    )

    css_vars = lambda mode: ";".join(f"--{k}:{v}" for k, v in PAL[mode].items())
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(ticker)} — {html.escape(name)}</title>
<style>
  :root{{{css_vars("light")};--panel:#fff}}
  html[data-theme="dark"]{{{css_vars("dark")};--panel:#111}}
  @media (prefers-color-scheme:dark){{html:not([data-theme="light"]){{{css_vars("dark")};--panel:#111}}}}
  *{{box-sizing:border-box}} body{{margin:0;background:var(--page);color:var(--primary);
    font-family:system-ui,-apple-system,"Segoe UI",sans-serif}}
  .wrap{{max-width:1000px;margin:0 auto;padding:20px}}
  .head{{display:flex;justify-content:space-between;align-items:flex-end;gap:12px;flex-wrap:wrap}}
  h1{{font-size:20px;margin:0}} .sub{{color:var(--secondary);font-size:13px;margin-top:2px}}
  .hero{{text-align:right}} .hero .px{{font-size:28px;font-weight:700}}
  .hero .dl{{font-size:14px;font-weight:600}} .up{{color:var(--good)}} .down{{color:var(--bad)}}
  .legend{{display:flex;gap:14px;flex-wrap:wrap;margin:12px 0 4px;font-size:12px;color:var(--secondary)}}
  .lg i{{display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:5px;vertical-align:middle}}
  .card{{background:var(--surface);border:1px solid var(--grid);border-radius:12px;padding:10px;position:relative}}
  svg{{display:block;width:100%;height:auto;touch-action:none}}
  .grid{{stroke:var(--grid);stroke-width:1}} .rsiband{{fill:var(--bandfill);opacity:.5}}
  .rsiline{{stroke:var(--axis);stroke-width:1;stroke-dasharray:3 3}}
  .ytick,.xtick{{fill:var(--muted);font-size:10.5px;font-variant-numeric:tabular-nums}}
  .ytick{{text-anchor:end}} .xtick{{text-anchor:middle}} .endlab{{font-size:11px;font-weight:600}}
  #cross{{stroke:var(--axis);stroke-width:1;opacity:0}} #dot{{opacity:0}}
  .tip{{position:absolute;pointer-events:none;background:var(--panel);border:1px solid var(--grid);
    border-radius:8px;padding:8px 10px;font-size:12px;opacity:0;transform:translate(-50%,-115%);
    white-space:nowrap;box-shadow:0 4px 14px rgba(0,0,0,.18);font-variant-numeric:tabular-nums}}
  .tip b{{display:block;margin-bottom:4px;font-size:11px;color:var(--secondary)}}
  .tip s{{display:inline-block;width:8px;height:8px;border-radius:2px;margin-right:5px;text-decoration:none}}
  .bar{{display:flex;gap:8px;margin:14px 0 4px}}
  button{{background:var(--surface);color:var(--primary);border:1px solid var(--grid);border-radius:8px;
    padding:6px 12px;font-size:12.5px;cursor:pointer}} button:hover{{border-color:var(--s1)}}
  table{{border-collapse:collapse;width:100%;font-size:12px;font-variant-numeric:tabular-nums;margin-top:8px}}
  th,td{{text-align:right;padding:4px 8px;border-bottom:1px solid var(--grid)}} th{{color:var(--secondary)}}
  td:first-child,th:first-child{{text-align:left}} #tableview{{display:none}}
</style></head>
<body><div class="wrap">
  <div class="head">
    <div><h1>{html.escape(ticker)} · {html.escape(name)}</h1>
      <div class="sub">Close + EMA 20/50/200 · RSI(14) · as of {html.escape(as_of)}</div></div>
    <div class="hero"><div class="px">{_fmt(last_close)}</div>
      <div class="dl {dcls}">{"+" if delta >= 0 else ""}{delta:.2f}% · RSI {_fmt(last_rsi, 1)}</div></div>
  </div>
  <div class="legend">{"".join(legend)}</div>
  <div class="card" id="card">
    <svg id="svg" viewBox="0 0 {W} {H}" preserveAspectRatio="xMidYMid meet"
         role="img" aria-label="Price and RSI chart for {html.escape(ticker)}">
      {"".join(grid)}{"".join(ylab)}{"".join(xlab)}
      {rband}{rlines}
      <text x="{PX0}" y="{RY0 - 6}" class="ytick" style="text-anchor:start">RSI(14)</text>
      {"".join(paths)}{rpath}{"".join(endlabels)}
      <line id="cross" x1="0" y1="{PY0}" x2="0" y2="{RY1}"/>
      <circle id="dot" r="3.5" fill="var(--s1)"/>
    </svg>
    <div class="tip" id="tip"></div>
  </div>
  <div class="bar">
    <button id="tbtn">Table view</button>
    <button id="thm">Toggle light/dark</button>
  </div>
  <div id="tableview"><table><thead><tr><th>Date</th><th>Close</th><th>EMA20</th><th>EMA50</th>
    <th>EMA200</th><th>RSI</th></tr></thead><tbody>{trows}</tbody></table></div>
</div>
<script>
const D={json.dumps(data)};
const svg=document.getElementById('svg'),card=document.getElementById('card'),tip=document.getElementById('tip'),
  cross=document.getElementById('cross'),dot=document.getElementById('dot');
const NAMES=['Close','EMA20','EMA50','EMA200','RSI'],COLS=['--s1','--s2','--s3','--s4','--s1'];
const VB={W},PY0={PY0};
function nearest(px){{let best=0,bd=1e9;for(let i=0;i<D.xs.length;i++){{const d=Math.abs(D.xs[i]-px);if(d<bd){{bd=d;best=i}}}}return best}}
function move(ev){{const r=svg.getBoundingClientRect(),sx=(ev.clientX-r.left)/r.width*VB;
  const i=nearest(sx),x=D.xs[i];cross.setAttribute('x1',x);cross.setAttribute('x2',x);cross.style.opacity=.8;
  const row=D.rows[i];const cy=(ev.clientY-r.top);
  tip.textContent='';
  const hd=document.createElement('b');hd.textContent=D.dates[i];tip.appendChild(hd);
  for(let k=0;k<5;k++){{if(row[k]==='-')continue;
    const sw=document.createElement('s');sw.style.background='var('+COLS[k]+')';tip.appendChild(sw);
    tip.appendChild(document.createTextNode(NAMES[k]+' '+row[k]));tip.appendChild(document.createElement('br'));}}
  tip.style.opacity=1;
  const cardR=card.getBoundingClientRect();tip.style.left=(ev.clientX-cardR.left)+'px';tip.style.top=cy+'px';
  dot.style.opacity=1;dot.setAttribute('cx',x);
}}
svg.addEventListener('pointermove',move);
svg.addEventListener('pointerleave',()=>{{tip.style.opacity=0;cross.style.opacity=0;dot.style.opacity=0}});
document.getElementById('tbtn').onclick=()=>{{const t=document.getElementById('tableview');
  t.style.display=t.style.display==='block'?'none':'block'}};
document.getElementById('thm').onclick=()=>{{const h=document.documentElement;
  const cur=h.getAttribute('data-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');
  h.setAttribute('data-theme',cur==='dark'?'light':'dark')}};
</script></body></html>"""
